name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pull-requests: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Model Training and Tests
      run: |
        pytest > pytest_report.txt 2>&1

    - name: Set up CML
      uses: iterative/setup-cml@v1

    - name: Generate CML Report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## CI Pipeline Report" > report.md
        echo "### Pytest Sanity Test Results" >> report.md
        echo "\`\`\`" >> report.md
        cat pytest_report.txt >> report.md
        echo "\`\`\`" >> report.md

        if [ -f metrics.json ]; then
          echo "### Model Evaluation Metrics" >> report.md
          echo "\`\`\`json" >> report.md
          cat metrics.json >> report.md
          echo "\`\`\`" >> report.md
        else
          echo "### Model Evaluation Metrics: Not found (metrics.json was not generated)" >> report.md
        fi

        cml comment create --publish report.md